# Generated by Django 2.0 on 2019-04-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='名称')),
                ('image', models.ImageField(blank=True, upload_to='up_image', verbose_name='上传图片')),
                ('fiels', models.FileField(blank=True, upload_to='up_file', verbose_name='上传文件')),
                ('add_time', models.DateField(auto_now=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '上传文件和图片',
                'verbose_name_plural': '上传文件和图片',
            },
        ),
        migrations.DeleteModel(
            name='UpFile',
        ),
    ]
