# Generated by Django 2.0 on 2019-04-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upfile', '0002_auto_20190426_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileimage',
            name='fiels',
        ),
        migrations.AddField(
            model_name='fileimage',
            name='files',
            field=models.FileField(blank=True, upload_to='up_file', verbose_name='上传文件'),
        ),
        migrations.AlterModelTable(
            name='fileimage',
            table='file',
        ),
    ]
